sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
    access-key-id: LTAI5tMwyzncSq2dPupZqGfz
    access-key-secret: SHxlb2iKEOIwKsLvgYZhCA0rsFkRn5
    bucket-name: waizuilongwang
  redis:
    host: localhost
    port: 6379
    database: 1
  wechat:
    appid: wx8d5e5dd65874ba6d
    secret: d0ccac2ea9466a44bb6b9e4aa5e1400d